version: 2.1

executors:
  linter_exec:
    docker:
      - image: cogrob/publications:ci
    working_directory: /tmp/cogrob
    environment:
      FOO: "Foo"

jobs:
  linter:
    executor: linter_exec
    steps:
      - checkout:
          path: publications
      - run:
          name: Run Linter
          working_directory: publications
          command: |
            .scripts/bibtidy.bash articles.bib
            .scripts/bibtidy.bash book-chapters.bib
            .scripts/bibtidy.bash books.bib
            .scripts/bibtidy.bash conf-papers.bib
            .scripts/bibtidy.bash journal-issues.bib
            .scripts/bibtidy.bash reports.bib
            .scripts/bibtidy.bash theses.bib

            .scripts/bibparser.py
            .scripts/bibtidy.bash publications.bib
            rm *.original
      - run:
          name: Diff Patch
          working_directory: publications
          command: |
            git add -A
            git diff --cached > /tmp/linter.patch
      - store_artifacts:
          path: /tmp/linter.patch
      - run:
          name: Test Patch
          working_directory: publications
          command: |
            git status --porcelain > /tmp/status.txt
            cat /tmp/status.txt
            test -z "$(cat /tmp/status.txt)" || exit 1

workflows:
  version: 2
  lint_and_test:
    jobs:
      - linter
