version: 2.1

executors:
  linter_exec:
    docker:
      - image: cogrob/publications:ci
    working_directory: /tmp/cogrob
    environment:
      FOO: "Foo"

jobs:
  linter:
    executor: linter_exec
    steps:
      - checkout:
          path: publications
      - run:
          name: Run Linter
          working_directory: publications
          command: |
            .scripts/bibparser.py
            .scripts/bibtidy.bash publications.bib
            git diff
            test -z "$(git status --porcelain)" || exit 1

workflows:
  version: 2
  lint_and_test:
    jobs:
      - linter
