#!/usr/bin/env bash
bibtex-tidy "$@" \
    --curly \
    --numeric \
    --space 2 \
    --align \
    --sort \
        type \
    --sort-fields \
        abstract \
        address \
        annote \
        author \
        bibsource \
        biburl \
        booktitle \
        category \
        chapter \
        comment \
        copyright \
        day \
        doi \
        editor \
        editors \
        eprint \
        institution \
        isbn \
        issn \
        journal \
        key \
        keywords \
        location \
        metadata \
        month \
        note \
        number \
        on \
        organization \
        pages \
        pdf \
        publisher \
        school \
        series \
        shorttitle \
        timestamp \
        title \
        type \
        url \
        urldate \
        volume \
        year \
    --strip-comments \
    --omit \
        date-added \
        date-modified

./.scripts/sort_bib.py "$@"